apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: example-minimal-cluster
spec:
  teamId: "example" # needs to be identitical with the name prefix (example-)
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    example:  # database owner
    - superuser
    - createdb
  databases:
    exampledb: example  # dbname: owner
  postgresql:
    version: "14"